name: pinwheel
description: A flutter plugin for the Pinwheel Link SDK.
version: 3.1.0
homepage: https://github.com/underdog-tech/pinwheel-flutter-sdk
documentation: https://github.com/underdog-tech/pinwheel-flutter-sdk

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ">=8.3.3 <9.0.0"
  built_collection: ">=5.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  built_value_generator: ">=8.3.3 <9.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.getpinwheel.pinwheel
        pluginClass: PinwheelPlugin
      ios:
        pluginClass: PinwheelPlugin
